# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'all_camp_det_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(317, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 181, 21))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 60, 181, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_basic_details = QtWidgets.QPushButton(self.widget)
        self.pushButton_basic_details.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_basic_details.setObjectName("pushButton_basic_details")
        self.verticalLayout.addWidget(self.pushButton_basic_details)
        self.pushButton_demand_n_feedback = QtWidgets.QPushButton(self.widget)
        self.pushButton_demand_n_feedback.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_demand_n_feedback.setObjectName("pushButton_demand_n_feedback")
        self.verticalLayout.addWidget(self.pushButton_demand_n_feedback)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Select one of these</span></p></body></html>"))
        self.pushButton_basic_details.setText(_translate("Dialog", "Basic Details"))
        self.pushButton_demand_n_feedback.setText(_translate("Dialog", "Demand and Feedback"))
